PATH="${HOME}/.bin:${PATH}"

export ZSH="${HOME}/.oh-my-zsh"

ZSH_THEME="spaceship"

SPACESHIP_PROMPT_ADD_NEWLINE="false"
SPACESHIP_DOCKER_PREFIX=""
SPACESHIP_KUBECONTEXT_PREFIX=""
SPACESHIP_KUBECTL_PREFIX=""
SPACESHIP_KUBECONTEXT_SUFFIX=""
SPACESHIP_KUBECONTEXT_SHOW=false
SPACESHIP_KUBECTL_SHOW=false
SPACESHIP_KUBECTL_SUFFIX=""
SPACESHIP_DOCKER_SUFFIX=""
SPACESHIP_DOCKER_CONTEXT_SHOW=false
SPACESHIP_USER_SHOW="true"
SPACESHIP_DOCKER_SHOW="false"
SPACESHIP_PROMPT_SEPARATE_LINE="false"

CASE_SENSITIVE="true"

plugins=(git history-substring-search zsh-completions zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh